{% set version = "0.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-glmpca
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/glmpca_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/glmpca/glmpca_{{ version }}.tar.gz
  sha256: 048a9cdb303279275aa2b23bb01777dffdeaec0752709b382c2289f21e70b20b

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
  run:
    - r-base
    - r-mass

test:
  commands:
    - $R -e "library('glmpca')"           # [not win]
    - "\"%R%\" -e \"library('glmpca')\""  # [win]

about:
  home: https://github.com/willtownes/glmpca
  license: Artistic-2.0
  summary: Implements a generalized version of principal components analysis (GLM-PCA) for dimension reduction of non-normally distributed data such as counts or binary matrices. Townes FW, Hicks SC, Aryee MJ, Irizarry RA (2019) <doi:10.1101/574574>. Townes FW (2019) <arXiv:1907.02647>.
  license_family: OTHER
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: glmpca
# Title: Dimension Reduction of Non-Normally Distributed Data
# Version: 0.1.0
# Description: Implements a generalized version of principal components analysis (GLM-PCA) for dimension reduction of non-normally distributed data such as counts or binary matrices. Townes FW, Hicks SC, Aryee MJ, Irizarry RA (2019) <doi:10.1101/574574>. Townes FW (2019) <arXiv:1907.02647>.
# Authors@R: c(person("F. William", "Townes", email = "will.townes@gmail.com", role = c("aut", "cre", "cph")), person("Kelly", "Street", email = "street.kelly@gmail.com", role="aut"), person("Jake", "Yeung", email = "jakeyeung@gmail.com", role="ctb"))
# License: Artistic-2.0
# Depends: R (>= 3.6), stats
# Imports:
# Suggests: knitr, MASS, testthat, covr, ggplot2
# URL: https://github.com/willtownes/glmpca
# BugReports: https://github.com/willtownes/glmpca/issues
# VignetteBuilder: knitr
# LazyData: false
# RoxygenNote: 6.1.1
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2019-09-13 22:06:37 UTC; townesf
# Author: F. William Townes [aut, cre, cph], Kelly Street [aut], Jake Yeung [ctb]
# Maintainer: F. William Townes <will.townes@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-09-27 10:50:05 UTC
